### ISSUE TITLE
Missing RSA's private key encryption and public key decryption

### ISSUE THREAD

**Issue by zhangdekui** [golang-module/dongle#13]
## Feature Request

Golang's standard library only has public key encryption and private key decryption, It would be perfect if there is private key encryption and public key decryption

**Comment by gouguoyin** [comment]
Private key encryption and public key decryption are not commonly used

**Comment by gouguoyin** [comment]
`v0.2.5` released and added `rsa` support for long plaintext `private key encryption` and `public key decryption`

https://github.com/golang-module/dongle#2rsa-encrypt-by-private-key-and-decrypt-by-public-key
