### ISSUE TITLE
md5 error

### ISSUE THREAD

**Issue by hq-zhonger** [golang-module/dongle#16]
![6](https://user-images.githubusercontent.com/78897251/208293864-f1a2886f-d7ec-40dd-8de1-3bb60cb76a23.PNG)

**Comment by gouguoyin** [comment]
Please view the document https://github.com/golang-module/dongle#encrypt-by-md5

```go
dongle.Encrypt.FromString("hello world").ByMd5().ToHexString()
```

<img width="860" alt="image" src="https://user-images.githubusercontent.com/13517412/208294408-2d3f9a4d-90aa-4b6a-b1b9-5845c9c177e5.png">
