### ISSUE TITLE
Expect to add ed25519 digital signature algorithm

### ISSUE THREAD

**Issue by xflcx1991** [golang-module/dongle#9]
## Feature Request

**Is your feature request related to a problem? Please describe:**

在需要高性能高安全的需求时，ed25519算法是一个很好的选择
**Describe the feature you'd like:**

实现Go 1.13起（https://pkg.go.dev/golang.org/x/crypto/ed25519），标准库自带的ed25519功能， crypto/ed25519模块。
**Describe alternatives you've considered:**

暂无
**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by gouguoyin** [comment]
Ed25519 signature and verification have been supported since version 0.2.1

**Comment by xflcx1991** [comment]
0.2.1 有了ed25519
但是readme ed25519示例代码运行不了
1. 没有dongle.Sign.FromString("hello world").Ed25519(privateKey, dongle.Raw) 方法,应该是 ByEd25519
2. dongle.Raw 是啥,哪里定义的？
@gouguoyin

**Comment by xflcx1991** [comment]
> // 编码模式常量
> const (
> 	RAW    encodingMode = "raw"
>	HEX    encodingMode = "hex"
>	BASE64 encodingMode = "base64"
> )
原来是dongle.RAW

**Comment by gouguoyin** [comment]
Thanks, the next version will be fixed.

**Comment by gouguoyin** [comment]
Fixed in v0.2.2

https://github.com/golang-module/dongle/releases/tag/v0.2.2
